keys:
  - DEPLOYER_KEY
  - ETHERSCAN_API_KEY
  - RPC_URL

profiles:
  sepolia:
    DEPLOYER_KEY: dev/DEPLOYER_KEY
    RPC_URL: =https://ethereum-sepolia-rpc.publicnode.com
  zksync-sepolia:
    DEPLOYER_KEY: dev/DEPLOYER_KEY
