name: test

on:
  workflow_dispatch:
  push:
    paths:
      - 'lib/**'
      - 'script/**'
      - 'src/**'
      - 'test/**'
      - '*.sh'
      - '.github/workflows/*.yml'
      - '.gitmodules'
      - 'remappings.txt'
      - 'foundry.toml'
      - 'justfile'

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run unit tests
        env:
          RPC_URL: ${{ secrets.NETWORK_RPC_URL }}
          DEPLOYER_KEY: ${{ secrets.DEPLOYER_KEY }}
        run: |
          just switch mainnet
          just test
        id: test
